version: "3.8"
services:
  mysql:
    image: mysql:${MYSQL_VERSION} # Read MYSQL_VERSION from .env file
    container_name: mysql-localhost-java
    restart: always
    env_file:
      - ".env" # File .env config
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:33006:3306" # Expose port 33006 from internal port 3306
    volumes:
      - "./data:/var/lib/mysql" # Folder database
      - "./log:/var/log/mysql" # Folder log
    security_opt:
      - seccomp:unconfined
networks:
  app-network:
    driver: bridge